### ISSUE TITLE
Preferred format for sound assets

### ISSUE THREAD

**Issue by sh-dave** [KTXSoftware/khamake#41]
Hi Robert,

I'm currently playing around with kha.Audio and was wondering about the used sound formats.
I have a couple of wav's in my assets folder, and when generating projects, i get ogg for flash/html5, wav for native targets. As my wav's are pretty big i'd like to use ogg on native targets as well. I looked through the khamake sources and see that the KoreExporter just copies the wavs. For testing, i copied the whole copySound() from FlashExporter.js, stuffed it in there and it's working (i get converted oggs and can play them in my app).

Now i was wondering how this could be integrated into khamake in a configurable way.
I did a basic implementation (only for KoreExporter) of a new field Project.assetOptions.

In the projects `khafile.js` you can use it like:

``` js
project.assetOptions.audio.preferredFormat = 'ogg';
```

And the KoreExporter.copySound() now just has a simple if and a copy of the flash exporters copySound() for the ogg branch.

``` js
    copySound(platform, from, to, encoders, options) {
        if (options.preferredFormat == 'ogg') {
            Files.createDirectories(this.directory.resolve(this.sysdir()).resolve(to).parent());
            Converter.convert(from, this.directory.resolve(this.sysdir()).resolve(to + '.ogg'), encoders.oggEncoder);
            return [to + '.ogg'];
        } else {
            fs.copySync(from.toString(), this.directory.resolve(this.sysdir()).resolve(to + '.wav').toString(), { clobber: true });
            return [to + '.wav'];
        }        
    }
```

Should i do a PR for this, or is it maybe just one usecase of what wighawag proposes in https://github.com/KTXSoftware/khamake/issues/34 and could be implemented better?

**Comment by RobDangerous** [comment]
Kha used to have different audio types until recently - Sound and Music. Music used to be compressed (typically using ogg) and was streamed at runtime. I simplified it to only use Sound objects but want to readd the options that were available before but in a more flexible way aka a stream method for Audio1 and a compression strength option for khamake. I do not want khafiles to define actual formats because that tends to be system specific - for example for html5 ideally sound is exported to ogg and acc so that all browsers can decode that internally.
